### ISSUE TITLE
IsNot operator is handled incorrectly for sqlite >= 3.21

### ISSUE THREAD

**Issue by cldellow** [cldellow/sqlite-parquet-vtable#26]
While testing https://github.com/cldellow/sqlite-parquet-vtable/pull/25, the random tests on Ubuntu 18.04 cropped up this issue:

10 rows: SELECT quote(ts_5), quote(bool_0), quote(int32_3), quote(int8_1), quote(ts_5), quote(string_7), quote(binary_10), quote(ts_5), quote(binary_10), quote(string_8), quote(int32_3), quote(binary_10), quote(int16_2), quote(int8_1) FROM nulls WHERE bool_0 IS NOT 0 LIMIT 10
Traceback (most recent call last):
  File "./tests/test-random", line 109, in <module>
    test_db(db_file, extension_file, ['nulls', 'no_nulls'])
  File "./tests/test-random", line 104, in test_db
    test_table(conn, table)
  File "./tests/test-random", line 96, in test_table
    test_statement(conn, table, column_values, all_values)
  File "./tests/test-random", line 80, in test_statement
    raise ValueError('ruhroh')

Follow up to see if this is a general issue or something about the 18.04 build. The 18.04 build also had issues in arrow at first, although the rest of the suite passed, so I expect this is a legit bug.

**Comment by cldellow** [comment]
Hm, this also fails on 18.04:

9 rows: SELECT quote(string_8) FROM nulls WHERE ts_5 <= 493603200000 AND binary_10 <> X'09'

In fact, the random tests on 18.04 seem to reliably produce failures. Hopefully just a test framework false positive from using different python libraries?

**Comment by cldellow** [comment]
The 18.04 build now generates a busted binary due to missing symbol from icu: _ZN6icu_606LocaleC1Ev

Fallout from https://github.com/cldellow/sqlite-parquet-vtable/commit/76fb058dd750f3554c5a7b09355701c78a74e349 ? Is it broken on 16.04, too?

**Comment by cldellow** [comment]
https://github.com/cldellow/sqlite-parquet-vtable/commit/0aa98ae1a59c6edf99a4fd4e06056cc346804246 fixes the build on 18.04

**Comment by cldellow** [comment]
```
.load build/linux/libparquet
CREATE VIRTUAL TABLE IF NOT EXISTS nulls1 USING parquet('/home/cldellow/sqlite-parquet-vtable/parquet-generator/99-rows-nulls-1.parquet');
SELECT quote(int8_1) FROM nulls1 WHERE rowid <> 94 AND bool_0 IS NOT 0;
```

fails on 18.04, passes on 16.04.

Gets 5 rows on 18.04, 55 on 16.04.

18.04 has g++ 7.3, python 3.6.5 w/sqlite 3.22 vs 16.04's g++ 5.5, python 3.5.2 w/sqlite 3.11

**Comment by cldellow** [comment]
Persists on 18.04 even with optimizations disabled. Doesn't appear on 16.04 even when building with g++ 7.3. Will check if it appears for python and sqlite versions later.

**Comment by cldellow** [comment]
Aha, I lie. It does repro on 16.04, but not via the test harness, which is presumably because its python is pulling in the system's sqlite, which is v3.11.

If I run sqlite itself, which is built against 3.22, it repros.

**Comment by cldellow** [comment]
Also repros against 3.24.

**Comment by cldellow** [comment]
Doesn't repro against 3.11 built against http://sqlite.org/2016/sqlite-autoconf-3110000.tar.gz. Need to bisect to figure out where it begins to break.

**Comment by cldellow** [comment]
3.21's [release notes](https://www.sqlite.org/releaselog/3_21_0.html) say:

- Pass information about !=, IS, IS NOT, NOT NULL, and IS NULL constraints into the xBestIndex method of virtual tables.

Perhaps my impl of IS NOT is busted?

**Comment by cldellow** [comment]
Added test case, bisected, fails on 3.21. Will look some more later this week.

**Comment by cldellow** [comment]
The current code handles IsNot the same as !=, which is incorrect in the presence of nulls. Let's disable that optimization for the time being.

I expect there will be similar failures around IS -- curious why random testing didn't catch them. Will spend some tiem trying to get repros.
